# Generated by Django 5.0 on 2023-12-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0002_curso_entregable_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
