# Generated by Django 5.0 on 2023-12-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0003_alter_profesor_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='entrega',
            new_name='entregado',
        ),
    ]
